name: Simple build with no options enabled

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: make
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: run tests & sample code
        run: |
          ./mpBasicTest
          ./mpCommandLineArgsTest 1
          ./mpMyFirstApp
        working-directory: build/MYPROJECT-build/bin
