name: Rename project using CMakeTemplateRenamer before building.

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: textbook/git-checkout-submodule-action@2.0.0

      - name: Rename project, build, test
        run: |
          cd ..
          git clone https://github.com/tdowrick/CMakeTemplateRenamer
          # Renamer arguments are: Existing folder name new folder name, new project name, project description, new namespace[instead of mp::], delete git history[Y/N], python package name (optional)

          FOLDER_TO_CLONE=CMakeCatchTemplate
          NEW_FOLDER_NAME=WorkflowProject
          NEW_PROJECT_NAME_CAMELCASE=WorkflowProject
          NEW_PROJECT_NAME_LOWER_CASE=${NEW_PROJECT_NAME_CAMELCASE,,}
          NEW_PROJECT_NAME_CAPS=${NEW_PROJECT_NAME_CAMELCASE^^}
          NEW_SHORT_DESCRIPTION="Tom's project"
          NEW_NAMESPACE="tp"
          DEL_GIT_LOG=Y
          PYTHON_PACKAGE_NAME=pyTom

          yes Y | CMakeTemplateRenamer/rename.sh FOLDER_TO_CLONE NEW_PROJECT_NAME_CAMELCASE NEW_PROJECT_NAME_LOWER_CASE NEW_PROJECT_NAME_CAPS NEW_SHORT_DESCRIPTION NEW_NAMESPACE DEL_GIT_LOG PYTHON_PACKAGE_NAME

          cd WorkflowProject

          mkdir build
          cd build
          cmake ..
          make

          cd WORKFLOWPROJECT-build/bin

          # As we have renamed the project, the 
          ./tpBasicTest
          ./tpCommandLineArgsTest 1
          ./tpMyFirstApp
